### ISSUE TITLE
Synaptic looks bad

### ISSUE THREAD

**Issue by OlegWock** [baurigae/polar-night#2]
![2015-06-08 23 14 00](https://cloud.githubusercontent.com/assets/7430438/8052416/1d236ebc-0e90-11e5-98ed-0c79691fc7bb.png)

**Comment by baurigae** [comment]
Could you tell me what version of gtk/gnome you're running? The theme was made for Ubuntu 14.04 LTS (Gnome/gtk 3.10) and has not yet been updated.

**Comment by OlegWock** [comment]
I use Ubuntu 14.04 with Unity  with gtk version 3.10.8-0ubuntu1.4

**Comment by baurigae** [comment]
Looks like you might be running your theme as user, while Synaptic requires root? If you don't have it there, put the theme in `/usr/share/themes` - and make sure your permissions are set properly and recursively to read all files -  instead of `/home/>your username>/.themes, and reload in Unity Tweak Tool or another app you're using.
You might already have it in /usr/share, but without properly set permissions. Check that pls.

**Comment by OlegWock** [comment]
Thanks, it work
